### ISSUE TITLE
[DOCS] pod install failure from undocumented iOS minimum deployment target

### ISSUE THREAD

**Issue by chriszs** [jwplayer/jwplayer-react-native#11]
**Describe the bug**

When I run `pod install`, I get:

```
npm error [!] CocoaPods could not find compatible versions for pod "RNJWPlayer":
npm error   In Podfile:
npm error     RNJWPlayer (from `../../../node_modules/react-native-jw-media-player`)
npm error
npm error Specs satisfying the `RNJWPlayer (from `../../../node_modules/react-native-jw-media-player`)` dependency were found, but they required a higher minimum deployment target.
```

This goes away when I add an iOS minimum deployment target of `14.0` to my Expo target, supplanting the default minimum of `13.4`.

**To Reproduce**
Try to install the iOS pod into a project with a minimum deployment target of `13.4`.

**Expected behavior**
No failure to install, or documentation of the requirement.

**Screenshots / Visual evidence**
If applicable, add screenshots or recordings to help explain your problem. (Required if reproduction is not 100% reliable)

**Desktop (please complete the following information):**

```
System:
  OS: macOS 14.4.1
  CPU: (8) arm64 Apple M2
  Memory: 70.19 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.1
    path: ~/.asdf/installs/nodejs/18.17.1/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.asdf/installs/nodejs/18.17.1/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.asdf/plugins/nodejs/shims/npm
  Watchman:
    version: 2024.03.25.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/admin/.asdf/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /Users/admin/.asdf/shims/javac
  Ruby:
    version: 2.6.10
    path: /Users/admin/.asdf/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

**Comment by AmitaiB** [comment]
@chriszs tldr, this is expected behavior.

Although [RN 0.73's minimum iOS version is 13.4](https://github.com/facebook/react-native/pull/36795), the JWP iOS SDK [dropped support for iOS 12 & 13 in version 4.17.0](https://releases.jwplayer.com/ios-sdk-4.17.0---googleima-sdk-update-and-new-minimum-supported-ios-version-3gF36E), after [Google IMA did the same](https://developers.google.com/interactive-media-ads/docs/sdks/ios/client-side/history) in IMA iOS SDK 3.18.5 and 3.19.1, and given that less than 1% of iPhones run it (and less today than back then).

While it's true that IMA walked that back ~2 months later, I am aware of multiple security vulnerabilities in iOS 12 and 13 that have not been patched, which I imagine is motivating this movement — especially since [all devices that support iOS 13 also support iOS 15](https://b2c-contenthub.com/wp-content/uploads/2023/06/statista.jpeg?quality=50&strip=all).

Do you have a particular need to support iOS 13?

**Comment by chriszs** [comment]
I don't especially need it, but React Native's default is 13.4, and I was surprised at needing to configure that higher. Feels like it should be documented.
