### ISSUE TITLE
[ASK] [Android] Is there any controls visibility option in config for casting icon and volume control ?

### ISSUE THREAD

**Issue by fdobre** [jwplayer/jwplayer-react-native#13]
1. I would need to hide the casting icon for Android without removing totally the casting dependencies because they are used by another player. Is there any options to do that?

2. Is there any availability for mute/volume button?

Any response will be greatly appreciated.

Thank you!

**Comment by Jmilham21** [comment]
Hi @fdobre, thank you for the inquiry. I'll address them below, but for both it sounds like you'd need to customize the UI which would require a custom fork.

1. To clarify, you need the JWP Chromecast package in some instances but not all? And in those circumstances you don't need it, you want to hide the icon? 

This can be done via customizing the UI, and since this isn't a standard use case, we won't take this on ourselves, but it is also possible by targeting the id for the cast icon `center_cast_img` and either removing it or more safely setting its size to 0x0. Since this view is attached to a non-public view model, you can't just put it to `View.GONE`. I'd suggest creating an interface method in a fork of this repository that you can pass in a new prop, and depending on that value, when creating the Android player, set the height and width of the Cast Icon View to 0 in `setupPlayer`:

``` Java
if (prop.hasKey("hideCastIcon")) {
  // Confirm hideCastIcon is whatever value you like
  View castView = findViewById(com.longtailvideo.jwplayer.R.id.center_cast_img);
  castView.setLayoutParams(new LayoutParams(0,0));
}

2. This would also require customizing the UI if you want the button to be inside the player. Generally, I'd suggest creating a React button outside the player view and hooking it up to the `setVolume` method on the wrapper (0 would mute and 100 would set the player back to full volume). Alternatively, there is a Player function that hasn't been exposed in this wrapper in the Android SDK called `setMute`, which, as the name suggests, can toggle the mute status of the player. This would require adding a new JS interface and a new function in the Java code. If you need assistance, you can create a Feature Request for this, and we will eventually expose the `setMute` function. 

If you require the button to live in the player, I'd suggest looking at our BPA for [Custom UI](https://github.com/jwplayer/jwplayer-android-best-practice-apps/tree/main/CustomUi). This will show you how to add a custom View to the player view and hook it up to one or more of our ViewModels to drive the UI and functionality. This is out of scope for this project, so if this aligns with your needs, you'll need to implement this yourself.

**Comment by fdobre** [comment]
> ```java
> hideCastIcon
> ```

@Jmilham21  Big thank you for the answer!

 I would need to have the casting icon hidden for all JWP player instances but keep the `com.google.android.gms:play-services-cast-framework` dependecy for other non-JWP player types (like StreamAMG).
I tried RNJWPlayerUseGoogleCast = true in app/gradle file but that didn't seem to work.

Anyway setting the height and width of the Cast Icon View to 0 in setupPlayer (suggested by you above) sounds great!

**Comment by Jmilham21** [comment]
Ahh, well, it sounds like you may not actually need the JWP Android cast SDK at all. If this is the case, you could set `RNJWPlayerUseGoogleCast = false` and then manually import the `com.google.android.gms:play-services-cast-framework` into your Android code. Either way, it sounds like you should be able to take the next steps! Glad to be of help.
