### ISSUE TITLE
[ASK] How do we render a media list?

### ISSUE THREAD

**Issue by dominictobias** [jwplayer/jwplayer-react-native#47]
**What isn't clear?**

Trying to render a list of videos.

The following API to list Media is missing many fields: https://docs.jwplayer.com/platform/reference/get_v2-sites-site-id-media

It returns an array of items like: 

```json
{
  "created": "2024-05-28T11:40:10+00:00",
  "duration": 1469.0780029296875,
  "error_message": null,
  "external_id": "4DOYxBQX-event-ONhCYWny",
  "hosting_type": "hosted",
  "id": "NJzw7KyI",
  "last_modified": "2024-05-28T12:14:23+00:00",
  "media_type": "video",
  "metadata": {
    "author": null,
    "category": null,
    "custom_params": {
      "cdtv_show": "First Mover",
      "channel_id": "/tv/first-mover",
      "channel_type": "cdtv",
      "livestream_channel_id": "4DOYxBQX"
    },
    "description": null,
    "external_id": "4DOYxBQX-event-ONhCYWny",
    "language": null,
    "permalink": null,
    "protection_rule_key": null,
    "publish_end_date": null,
    "publish_start_date": "2024-05-28T11:40:11+00:00",
    "tags": [],
    "title": "First Mover 2024-05-28 at 11:40"
  },
  "mime_type": null,
  "relationships": {},
  "schema": null,
  "source_url": null,
  "status": "ready",
  "trim_in_point": null,
  "trim_out_point": null,
  "type": "media"
}
```

But in this library a PlaylistItem looks like this:

```ts
interface PlaylistItem {
    file: string;
    sources?: Source[];
    image?: string;
    title?: string;
    description?: string;
    mediaId?: string;
    adSchedule?: AdSchedule[];
    adVmap?: string;
    tracks?: Track[];
    recommendations?: string;
    startTime?: number;
    autostart?: boolean;
  }
  ```
  
  I can query e.g. https://docs.jwplayer.com/platform/reference/get_v2-sites-site-id-media-media-id-playback-json to get more info for EACH media ID, but this is extremely inefficient? Also it contains `sources` but not `file` but I guess we just pic a source for that?
  
  How are we supposed to render videos in our media list considering no `file` or `sources` are provided by the API?

**Comment by Jmilham21** [comment]
Hey @dominictobias , I'll break this up to hopefully answer all your asks:

1. The first link you shared is for the Management API, and this isn't ideal for consumption by any of our players. We don't have an interface for parsing the result, and since it requires your API key and secret, we wouldn't recommend it to drive content in your application code. However, if you requested info from your own API that manages the callback for the management API, you could return a pre-fabricated config to load into your app, or build upon it in app. 

2. The `PlaylistItem` is from the legacy codebase. It's a custom object that isn't directly correlated to the SDK objects and builders. We'd recommend using the `JwPlaylistItem` instead, a more 1:1 mapping of the builder classes available on both SDKs. The assumption in our code is you are using the `JwPlaylistItem` and we only fallback to `PlaylistItem` if you explicitly tell us, or the parsing of the config fails as a `JwPlaylistItem`. This doesn't consume every field from the Delivery API or Management API, but it does leverage nearly every possible builder in Android and iOS SDK.

   2. Depending on your goal, it could be wise to get the whole list of media from your API that leverages the Management API (to keep your API secrets out of application code), then either build up a custom object with mapping of your needs or use [this](https://docs.jwplayer.com/platform/reference/get_v2-media-media-id) as a template to request the playlist config from our Delivery API and either modify that or simply plug in the response for the item as a `JwPlaylistItem`.

4. To your point about the Delivery API not surfacing a `file`, this is true for content hosted with us, but you can get the manifest file from what is typically the first source in the set like seen below (unless you are using a custom ingest profile, you should get an HLS manifest):
```json
{
          "file": "https://cdn.jwplayer.com/manifests/YOUR-ID.m3u8",
          "type": "application/vnd.apple.mpegurl"
}
```

If you have any more questions about this, please reach out to our support team. We want to keep this repo related to implementation rather than platform questions.

**Comment by dominictobias** [comment]
Thanks I got it working by combining the data. Seems a shame there isn't an API that can filter/search on the media list and return useful data like file/images/tracks/sources but there you go!

When switching to `JwConfig` `backgroundAudioEnabled` isn't an option: https://github.com/jwplayer/jwplayer-react-native?tab=readme-ov-file#background-audio

How can we have background audio with the new config?

**Comment by dominictobias** [comment]
Also this in the README doesn't make sense to me:

```
iOS Advertising
Follow this step to set up advertising with IMA or DAI:

In the Podfile ext{}, add $RNJWPlayerUseGoogleIMA = true. This setting will add GoogleAds-IMA-iOS-SDK to the pod.
```

Podfile doesn't use `{}` syntax, nor does it have an `ext` section?
