### ISSUE TITLE
[BUG] Enabling background audio on Android 14 or later causes a crash

### ISSUE THREAD

**Issue by Solly74** [jwplayer/jwplayer-react-native#53]
**Describe the bug**
React Native: 0.73.4
@jwplayer/jwplayer-react-native: 1.0.1 
Enabling background audio on Android 14 causes the video to crash with the following trace.

![Screenshot 2024-06-26 at 12 47 07](https://github.com/jwplayer/jwplayer-react-native/assets/13263485/92084ad0-1f57-4c4f-a538-e5a30ec5be11)

**Comment by morrieinmaas** [comment]
I think you can check for/set minsdkversion in build.gradle to be >=34 and then set foreground service type in manifest.xml (https://developer.android.com/about/versions/14/changes/fgs-types-required, seems required from 34 onward)

**Comment by Solly74** [comment]
@morrieinmaas is background audio a foreground service? It was my understanding it was a background service, hence the need for https://docs.jwplayer.com/players/docs/android-enable-background-audio

**Comment by morrieinmaas** [comment]
Hey @Solly74 - well just saw that in my emails and thought hang on a second that looks somewhat familiar. The error stack says foreground service so thought that's relevant. anyway, haven't looked at any of your code. Jus thought it might help 😄 

you see that the jwplayer.backgroundservice seems to try enable a foreground service so i guess that that needs to be explicitly set in android 14. anyway, again just thought this might help.

**Comment by Jmilham21** [comment]
This is resolved via this [commit](https://github.com/jwplayer/jwplayer-react-native/commit/8abc73089adc2672fc7d0685e01c086f73ccc439). The change will be in the next release (1.0.2: date TBD)

You are correct, @morrieinmaas that the service type must be specified with Android 14 and higher. 

@Solly74 The background audio service has to be foreground service since it is playing audio and interacts with the main thread. See the developer docs explaining the Service types [here](https://developer.android.com/develop/background-work/services#Types-of-services).
